spring.application.name=SpringJdbcEx
spring.datasource.url=jdbc:postgresql://localhost:5432/Sarvesh
spring.datasource.username=postgres
spring.datasource.password=Sarvesh123
spring.datasource.driver-class-name=org.postgresql.Driver