spring.application.name=SringEcom
spring.datasource.url=jdbc:postgresql://localhost:5432/Sarvesh
spring.datasource.username=postgres
spring.datasource.password=Sarvesh123
spring.jpa.hibernate.ddl-auto=update
